### ISSUE TITLE
Error when included in project with butterknife 

### ISSUE THREAD

**Issue by RoryKelly** [JakeWharton/kotterknife#55]
in an app I'm slowly moving over to kotlin in Build.gradle I add in:

``` 
 kapt 'com.jakewharton:butterknife-compiler:8.5.1'
  compile 'com.jakewharton:butterknife:8.5.1'
  compile 'com.jakewharton:kotterknife:0.1.0-SNAPSHOT'
```
When I Build it fails with:

```
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lbutterknife/BuildConfig;
Error:com.android.dex.DexException: Multiple dex files define Lbutterknife/BuildConfig;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:608)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:563)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:545)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:167)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:194)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.mergeDexes(DexArchiveMergerCallable.java:66)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:54)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:37)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lbutterknife/BuildConfig;
```

**Comment by g00m** [comment]
same here but with: 

    compile 'com.jakewharton:butterknife:8.6.0'
    compile 'com.jakewharton:kotterknife:0.1.0-SNAPSHOT'

**Comment by dashracer** [comment]
I have the same problem with @RoryKelly 

really need help

**Comment by CodyEngel** [comment]
The error is saying that there are multiple inclusions of Butterknife. Have either of you tried removing butterknife from the dependency?

**Comment by RoryKelly** [comment]
Yes Removing the butterknife dependency fixes the issue. Though if you have a large project and want to migrate to kotterknife it would be very useful to be able to use both simultaneously. 

I have embedded the kotlin file in my project for now.

**Comment by Evanuke** [comment]
Is there any chance to avoid this problem? I got exact same error. I want to use 3rd party library, based on Java, which use Butterknife, but I already use in my project Kotterknife because it's fully written in Kotlin :(

**Comment by CodyEngel** [comment]
I would file an issue with the library that uses ButterKnife or just not
use a library that forces you use ButterKnife. It's a terrible idea on the
authors part to include a library like that for their own library.
